# Generated by Django 4.0 on 2021-12-14 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nationality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="person",
            name="nationality",
            field=models.ForeignKey(
                db_column="nationality",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.Nationality",
            ),
        ),
    ]
